name: CI

on:
- push
- pull_request
- workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check with ${{ matrix.check }}
    strategy:
      matrix:
        check: [bluecheck, doc8, flake8, rstcheck, docs]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Run checks with tox
        run: |
          tox -e ${CHECK}
        env:
          CHECK: ${{ matrix.check }}

  test:
    runs-on: ubuntu-latest
    name: Test with Python ${{ matrix.python }}
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12', '3.13', '3.14', '3.15-dev']
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: |
            tox -e py
